### ISSUE TITLE
Cant check update

### ISSUE THREAD

**Issue by glannes31** [ResurrectionRemix/OTA#15]
Hello, i am a recently french user of resurrection remix rom. I wish to check the update with ota but it tell tha cant check update. Could you help me?

**Comment by varund7726** [comment]
Device?

**Comment by glannes31** [comment]
Galaxy note 3 Sm-N9005

**Comment by glannes31** [comment]
Hello. An idea for my problem? I have no ota_conf in RR folder. I tried to put in this folder the  example file on github but is not working

**Comment by andrewwrightt** [comment]
folder? just ota_conf

**Comment by glannes31** [comment]
I put ota_conf in RR folder but nothing. Always cant check update

**Comment by varund7726** [comment]
And what about ota.xml? Did you link github ota.xml in ota_conf?

**Comment by glannes31** [comment]
Ota.xml is not ota_conf.xml ?

**Comment by varund7726** [comment]
oh man your so confused...
ota.xml is different

and ota_conf is different
ota_conf has NO XML file extention

ota.xml HAS XML file extension

ota_conf must be in RR folder and it must contain link to ota.xml
ota.xml should be on your github 
ota.xml should look like this https://github.com/ResurrectionRemix/OTA/blob/master/hammerhead.xml

**Comment by glannes31** [comment]
Thks varund for your explanation. I try now

**Comment by glannes31** [comment]
Well ota_conf is a file wich contain a link to ota.xml . the ota.xml is named hammerhead.xml here. I got it?

**Comment by akhilnarang** [comment]
for hammerhead yep

**Comment by akhilnarang** [comment]
you can name it anything, just link correctly
also check README of OTA app, i updated it

**Comment by glannes31** [comment]
It doesnt work.... Cant check update...

**Comment by varund7726** [comment]
show me your ota_conf and ota.xml @glannes31

**Comment by glannes31** [comment]
Ota_conf

#
# OTA XML
#
# See ota_lollipop.xml for example
#
# Note:
# * Multiple devices can be added in the xml file
# * You can define any tags that end with 'Url'. These tags will be added in the UI automatically
#
ota_url=https://github.com/ResurrectionRemix/OTA/raw/master/hammerhead.xml
release_type=Stable
device_name=ro.rr.device
 
#
# VERSION
#
# A version can be a date or a number with characters
# A version source can be a 'property key' from build.prop or a 'uname -r' command line
# If a version is a number, leave the version_format empty. Otherwise, provide the date format
#
# Example with a property key 'ro.rr.version' : Parse the date 20150426 from 'ResurrectionRemix-M-v5.x.x-20150426-bacon'
#
# Version source: ro.modversion
# Version delimiter: -
# Version position: 3 (zero based)
# Version format: yyyyMMdd
#
# Example with 'uname -r': Parse the number 239 from '3.4.107~AK.239.OPO.CM12.1'
#
# Version source: uname -r
# Version delimiter: .
# Version position: 3 (zero based)
# Version format:
#
version_source=ro.rr.version
version_delimiter=-
version_position=3
version_format=yyyyMMdd

Ota.xml is hammeread.xml

**Comment by varund7726** [comment]
and your device is NOTE3 ? why in the world would you point to hammerhead.xml?

**Comment by glannes31** [comment]
Well, Explain me where i point my file if my device is note3

**Comment by varund7726** [comment]
send me a screenshot of your OTA app

**Comment by akhilnarang** [comment]
fork the repo to your account
make an xml of your own
point to that

**Comment by glannes31** [comment]
I dont use an ota app . i use the system ota in parameter Configuration Updates

**Comment by varund7726** [comment]
That is the same thing

**Comment by glannes31** [comment]
https://drive.google.com/file/d/0B6vuLYGFHEYvZllEOEFva245N3M/view?usp=drivesdk

**Comment by glannes31** [comment]
Hello. Do you have an idea for my problem? Where i point my ota_conf ? What is the ota.xml for galaxy note 3?

**Comment by akhilnarang** [comment]
You have to make the xml -_- and point the conf to that

**Comment by glannes31** [comment]
I am a simply user not a dev..... Well i close the issue...

**Comment by varund7726** [comment]
omg you were a user? all this while i was thinking you are a maintainer.

you cant do anything then.. you will have to ask the maintainer of your device to fix the issue
