### ISSUE TITLE
Where is the ota links add?

### ISSUE THREAD

**Issue by kaankulahli** [ResurrectionRemix/OTA#17]
Hi , I added a ota_conf and seed.xml but where is the add in build ?

**Comment by kaankulahli** [comment]
I don't find it , help me please ?

**Comment by dragonGR** [comment]
Wut?

**Comment by kaankulahli** [comment]
How to add ota links on my unofficiall build. you don't write  how to make.

**Comment by dragonGR** [comment]
Place ota_conf on source dir
make sure in ota_conf you added the raw link in ota_url line
check here for example
https://github.com/dragonGR/OTA/blob/RR/ota_conf#L10

The rest is easy.
