### ISSUE TITLE
"Can't check update"

### ISSUE THREAD

**Issue by MoNTE48** [ResurrectionRemix/OTA#2]
Pls, look my repo https://github.com/MoNTE48/RR_ota
I copy ota_conf on my RR folder, but i see "Can't check update".

**Comment by akhilnarang** [comment]
Verify your xml with some xml verifier
Must be some mistakes in it

**Comment by MoNTE48** [comment]
There are no mistakes. All in the same way as you

**Comment by varund7726** [comment]
your xml is not well formed
you have entered & in the link which does not get parsed

here is your fixed xml

**Comment by MoNTE48** [comment]
Error in the & ? Ok, thank you!

**Comment by brateuuac3** [comment]
Where I can find ota_conf file or file what I need edit?
