### ISSUE TITLE
Help regarding OTA update YUREKA

### ISSUE THREAD

**Issue by puneeth777** [ResurrectionRemix/OTA#22]
Hi,
I am using YU YUREKA  device, i just installed ResurrectionRemix ROM but when i try checking for updates it say "can't check updates" when i check i dont have ota_conf and ota.xml files. So can someone please help me setup these files?

waiting for your reply
Thank you

**Comment by akhilnarang** [comment]
Its for the builder to setup not you

**Comment by puneeth777** [comment]
then how can i get OTA updates ??

**Comment by varund7726** [comment]
You'll have to ask your maintainer for that .

**Comment by puneeth777** [comment]
how can i contact me.? don't mind i am new to this sorry

**Comment by puneeth777** [comment]
how can i contact them ?
