### ISSUE TITLE
Can't check update

### ISSUE THREAD

**Issue by regalstreak** [ResurrectionRemix/OTA#7]
Here is my ota.xml and ota_conf: https://github.com/regalstreak/rr_ota
Am i doing something wrong?
I have checked my xml with a verifier and no errors were found.
Please help me. @varund7726 @westcripp 
Thanks in advance.

**Comment by varund7726** [comment]
@akhilnarang this is happening to a lot of users.can you check please? Its not happening to me but some others .I asked them to wipe data and cache of the app but doesn't work

**Comment by varund7726** [comment]
@regalstreak don't link ota_conf to raw

**Comment by regalstreak** [comment]
@varund7726 can you share your own ota_conf please bro?
Where do you all store it?

**Comment by akhilnarang** [comment]
https://github.com/ResurrectionRemix/OTA
Check the example ota_conf
I use that, and no issues

**Comment by regalstreak** [comment]
where do youll store ota_conf? On github itself naa? Why should i not link it to raw?

**Comment by akhilnarang** [comment]
@regalstreak why are you using ro.product.model?
That is not oneplus2
use ro.rr.device
ro.product.model is set dynamically on boot

**Comment by akhilnarang** [comment]
Yep you have to use raw that isn't the issue

**Comment by akhilnarang** [comment]
and version source should be ro.rr.version no ro.modversion

**Comment by regalstreak** [comment]
ota_url=https://raw.githubusercontent.com/regalstreak/rr_ota/marshmallow/ota.xml
release_type=Stable
device_name=ro.rr.device
version_source=ro.rr.version
version_delimiter=-
version_position=3
version_format=yyyyMMdd 

This looks right?

**Comment by akhilnarang** [comment]
Also https://github.com/regalstreak/android_device_oneplus_oneplus2/blob/cm-13.0/init/init_oneplus2.cpp#L48
ro.rr.device :)

**Comment by akhilnarang** [comment]
Compare the stuff with example ota_conf, the only thing you should change is ota_url, nothing else

**Comment by regalstreak** [comment]
ok ill try to do it tomorrow. Thanks for helping :D

**Comment by akhilnarang** [comment]
:+1: close issue if solved

**Comment by varund7726** [comment]
:+1:

**Comment by regalstreak** [comment]
Yes made it work :3
You were right @akhilnarang just needed to change the ota_url
Khali phukat time barbad kar diya :3
This is what fixed it : https://github.com/regalstreak/rr_ota/commit/1b84f727922c282f6be26c8a861a6d272fee0bde
Would be helpful to others too.
Issue solved, closing! Thanks.

**Comment by brateuuac3** [comment]
Where I can find "ota_conf" or "ota.xml" on my device?

**Comment by akhilnarang** [comment]
@brateuuac3 its on your device
ota.xml is online, ota_conf to be placed in root of rr source

**Comment by brateuuac3** [comment]
@akhilnarang What mean "online" and where is root of resorrection Remix? Can you write real address to file please?

**Comment by akhilnarang** [comment]
You can't access it on your phone
the maintainer for your device has to add the file

**Comment by brateuuac3** [comment]
So, how I can change ota url?

**Comment by akhilnarang** [comment]
tell maintainer to update it in the ota_conf

**Comment by brateuuac3** [comment]
This is my problem :/ 
![13285790_859451007520822_647253639_n](https://cloud.githubusercontent.com/assets/19596597/15591356/efc9fe04-239c-11e6-8bec-dda69bf635a5.png)

**Comment by brateuuac3** [comment]
This is my problem.... 
![13292805_859453194187270_108782818_n](https://cloud.githubusercontent.com/assets/19596597/15591427/5c8997de-239d-11e6-8489-7efe70d56ef1.png)

**Comment by akhilnarang** [comment]
tell your device maintainer to fix it...

**Comment by brateuuac3** [comment]
I will :) Thank you.

**Comment by kaankulahli** [comment]
Where is add your Ota links file ? (include seed.xml and ota_conf). I was add ResurrectionRemixOTA
