### ISSUE TITLE
mobile restart when incoming call

### ISSUE THREAD

**Issue by 1pawan** [ResurrectionRemix/OTA#9]
I recently install this awesome ROM in my redmi 2 
But here some major bug are present 
 When any incoming call come then mobile automatically restart and therefore call not received
So please solve this problem immediately

**Comment by akhilnarang** [comment]
That was a cm issue
Tell whoever builds to make a new build

**Comment by 1pawan** [comment]
But this cause my more loss 
And where to complained this issue
